name: Compile sus_su for x86_64

on:
  workflow_dispatch:

jobs:
  build-x86_64-sus_su:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Download and Unzip NDK
      run: |
        NDK_URL="https://dl.google.com/android/repository/android-ndk-r23b-linux.zip"
        NDK_ZIP="android-ndk-r23b-linux.zip"
        echo "Downloading NDK from $NDK_URL"
        curl -L -o $NDK_ZIP $NDK_URL
        echo "Unzipping NDK"
        unzip -q $NDK_ZIP -d android-ndk-r23b

    - name: Set up NDK environment
      run: |
        echo "ANDROID_NDK_HOME=$(pwd)/android-ndk-r23b/android-ndk-r23b" >> $GITHUB_ENV
        echo "PATH=${ANDROID_NDK_HOME}/toolchains/llvm/prebuilt/linux-x86_64/bin:$PATH" >> $GITHUB_ENV

    - name: Compile sus_su for x86_64
      run: |
        cd susfs4ksu-gki-android12-5.10/susfs4ksu-gki-android12-5.10/sus_su/jni
        ${ANDROID_NDK_HOME}/ndk-build NDK_PROJECT_PATH=. APP_BUILD_SCRIPT=./Android.mk APP_ABI=x86_64

    - name: Rename and prepare binary
      run: |
        mkdir -p compiled_binaries
        mv susfs4ksu-gki-android12-5.10/susfs4ksu-gki-android12-5.10/sus_su/jni/libs/x86_64/sus_su compiled_binaries/sus_su_x86_64

    - name: Upload compiled binary
      uses: actions/upload-artifact@v4
      with:
        name: sus_su_x86_64_binary
        path: compiled_binaries/sus_su_x86_64